
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: "${DOCKER_USER_ID:-1000}"
        GROUP_ID: "${DOCKER_GROUP_ID:-1000}"
        USERNAME: "${DOCKER_USERNAME:-rails}"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rails_development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  bundle_cache:
  node_modules:
  postgres_data:
